steps:
  - name: "cytopia/pylint"
    id: "pylint"
    args:
      - "app.py"

  - name: "python"
    id: "download-dependencies"
    args:
      - pip
      - install
      - -r
      - requirements.txt
      - --target
      - ./package

  - name: "javieraviles/zip"
    id: "zip-dependencies"
    args:
      - zip
      - -r
      - ../fail-open-lambda.zip
      - .
    waitFor: ["download-dependencies"]
    dir: package

  - name: "javieraviles/zip"
    id: "zip-lambda"
    args:
      - zip
      - -g
      - fail-open-lambda.zip
      - app.py
    waitFor: ["download-dependencies"]

  - name: "amazon/aws-cli"
    id: "upload-us-east-1"
    entrypoint: "scripts/publish.sh"
    env:
      - "BUCKET=cyral-dev-artifacts"
      - "BUCKET_KEY_PREFIX=fail-open"
      - "VERSION=$BUILD_ID"
      - "APPEND_REGION=false"
    args:
      - us-east-1
    waitFor: ["zip-lambda"]
    secretEnv: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]

availableSecrets:
  secretManager:
    - versionName: projects/cyral-dev/secrets/github-aws-private-key-secret/versions/1
      env: AWS_SECRET_ACCESS_KEY
    - versionName: projects/cyral-dev/secrets/github-aws-private-key-id/versions/1
      env: AWS_ACCESS_KEY_ID
