steps:
  - name: "python"
    id: "download-dependencies"
    args:
      - pip
      - install
      - -r
      - requirements.txt
      - --target
      - ./package

  - name: "javieraviles/zip"
    id: "zip-dependencies"
    args:
      - zip
      - -r
      - fail-open-lambda.zip
      - ./package
    waitFor: ["download-dependencies"]

  - name: "javieraviles/zip"
    id: "zip-lambda"
    args:
      - zip
      - -g
      - fail-open-lambda.zip
      - app.py
    waitFor: ["zip-dependencies"]

  - name: "gcr.io/cyral-dev/awscli"
    id: "upload-us-east-1"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-east-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  - name: "gcr.io/cyral-dev/awscli"
    id: "publish-us-east-1"
    args:
      - s3api
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-east-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-east-1"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    
  - name: "gcr.io/cyral-dev/awscli"
    id: "upload-us-east-2"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-east-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  - name: "gcr.io/cyral-dev/awscli"
    id: "publish-us-east-2"
    args:
      - s3api
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-east-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-east-2"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      
  - name: "gcr.io/cyral-dev/awscli"
    id: "upload-us-west-1"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-west-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  - name: "gcr.io/cyral-dev/awscli"
    id: "publish-us-west-1"
    args:
      - s3api
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-west-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-west-1"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  - name: "gcr.io/cyral-dev/awscli"
    id: "upload-us-west-2"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-west-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  - name: "gcr.io/cyral-dev/awscli"
    id: "publish-us-west-2"
    args:
      - s3api
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-west-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-west-2"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY



secrets:
  - kmsKeyName: projects/cyral-dev/locations/global/keyRings/github-keyring/cryptoKeys/github-key
    secretEnv:
      AWS_ACCESS_KEY_ID: CiUAkKjghlJWeRIDhHwrrx+NIgKQEYSuYGIqgUszUgu6Dym7sr92Ej0AqZer5DfbPSkN9exrSFkQZN0isobw2Na7uo4l5QWQaKByeMiFCy75T9WFgL2C+HgzxkpcuUbq1IIVrf0r
      AWS_SECRET_ACCESS_KEY: CiUAkKjghlPCc6V+4CpDpGXABTdX5OUewVLos1RTPzLA3jE5HSXnElEAqZer5J5mUREoTg/oc1krd4tYnG9VoWd5udlJdjTiogBd4KcxWYj/ZVQLP7MBuxFwp4kjBb7CgeedaELrsmfam7yCblWr03zxFG9ENLJW83Q=