steps:
  - name: "python"
    id: "download-dependencies"
    args:
      - pip
      - install
      - -r
      - requirements.txt
      - --target
      - ./package

  - name: "javieraviles/zip"
    id: "zip-dependencies"
    args:
      - zip
      - -r
      - fail-open-lambda.zip
      - ./package
    waitFor: ["download-dependencies"]

  - name: "javieraviles/zip"
    id: "zip-lambda"
    args:
      - zip
      - -g
      - fail-open-lambda.zip
      - app.py
    waitFor: ["zip-dependencies"]

  - name: "amazon/aws-cli"
    id: "upload-us-east-1"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-east-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  - name: "amazon/aws-cli"
    id: "upload-us-east-2"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-east-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      
  - name: "amazon/aws-cli"
    id: "upload-us-west-1"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-west-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  - name: "amazon/aws-cli"
    id: "upload-us-west-2"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-west-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY



secrets:
  - kmsKeyName: projects/cyral-dev/locations/global/keyRings/github-keyring/cryptoKeys/github-key
    secretEnv:
      AWS_ACCESS_KEY_ID: CiUAkKjghrFlD5Evu7R+uUtWdshhQ0Zv6i5uLQi/VmKdZOTAx9fEEj4AqZer5L+klQsdc8NTYiYfQc45U2n7gfQG19tgCpGelO3g/1lQ9iCw60LMwcrLq6TtUVZ8gfxlXaVTSxlfSA==
      AWS_SECRET_ACCESS_KEY: CiUAkKjghl2uM7oc/xEzIZ1DYT8tSeJv/I7Ldz6wtxA24FjlPtu2ElIAqZer5PYUlrPMDwmPxv7Uxmc71+MISV6DMAPc9TcY+oCVd1FbrEgnkshok/Nqs18xePvL28hB1KIRajDzO1bY2n2rySneY/d9jMybDQ33Iv8R