steps:

  - name: "python"
    id: "download-dependencies"
    args:
      - pip
      - install
      - -r
      - requirements.txt
      - --target
      - ./package

  - name: "javieraviles/zip"
    id: "zip-dependencies"
    args:
      - zip
      - -r
      - ../fail-open-lambda.zip
      - .
    waitFor: ["download-dependencies"]
    dir: package

  - name: "javieraviles/zip"
    id: "zip-lambda"
    args:
      - zip
      - -g
      - fail-open-lambda.zip
      - app.py
    waitFor: ["zip-dependencies"]

  - name: "amazon/aws-cli"
    id: "upload-us-east-1"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-east-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
  - name: "amazon/aws-cli"
    id: "publish-us-east-1"
    args:
      - s3api
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-east-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-east-1"]
    secretEnv: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]

  - name: "amazon/aws-cli"
    id: "upload-us-east-2"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-east-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]

  - name: "amazon/aws-cli"
    id: "publish-us-east-2"
    args:
      - s3api
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-east-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-east-2"]
    secretEnv: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]

  - name: "amazon/aws-cli"
    id: "upload-us-west-1"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-west-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]

  - name: "amazon/aws-cli"
    id: "publish-us-west-1"
    args:
      - s3api
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-west-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-west-1"]
    secretEnv: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]

  - name: "amazon/aws-cli"
    id: "upload-us-west-2"
    args:
      - s3api
      - put-object
      - --bucket
      - cyral-public-assets-us-west-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda"]
    secretEnv: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]

  - name: "amazon/aws-cli"
    id: "publish-us-west-2"
    args:
      - s3api
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-west-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-west-2"]
    secretEnv: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]

availableSecrets:
  secretManager:
    - versionName: projects/cyral-dev/secrets/github-aws-key-secret/versions/3
      env: AWS_SECRET_ACCESS_KEY
    - versionName: projects/cyral-dev/secrets/github-aws-key-id/versions/3
      env: AWS_ACCESS_KEY_ID

