steps:
  # Download the AWS credentials
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - cp
      - gs://cyral-keys/cloudbuild_aws_credentials.enc
      - ./cloudbuild_aws_credentials.enc
    id: "get-aws-creds"

  # Decrypt the AWS creds
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --ciphertext-file=cloudbuild_aws_credentials.enc
      - --plaintext-file=/root/.aws/credentials
      - --location=global
      - --keyring=github-keyring
      - --key=github-key
    id: "decrypt-aws-key"
    volumes:
      - name: "aws"
        path: /root/.aws


  - name: "python"
    id: "download-dependencies"
    args:
      - pip
      - install
      - -r
      - requirements.txt
      - --target
      - ./package

  - name: "javieraviles/zip"
    id: "zip-dependencies"
    args:
      - zip
      - -r
      - fail-open-lambda.zip
      - ./package
    waitFor: ["download-dependencies"]

  - name: "javieraviles/zip"
    id: "zip-lambda"
    args:
      - zip
      - -g
      - fail-open-lambda.zip
      - app.py
    waitFor: ["zip-dependencies"]

  - name: "amazon/aws-cli"
    id: "upload-us-east-1"
    args:
      - s3api
      - --profile
      - cyral-production-public-assets
      - put-object
      - --bucket
      - cyral-public-assets-us-east-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda", "decrypt-aws-key"]
    volumes:
      - name: "aws"
        path: /root/.aws
  - name: "amazon/aws-cli"
    id: "publish-us-east-1"
    args:
      - s3api
      - --profile
      - cyral-production-public-assets
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-east-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-east-1"]
    volumes:
      - name: "aws"
        path: /root/.aws
    
  - name: "amazon/aws-cli"
    id: "upload-us-east-2"
    args:
      - s3api
      - --profile
      - cyral-production-public-assets
      - put-object
      - --bucket
      - cyral-public-assets-us-east-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda", "decrypt-aws-key"]
    volumes:
      - name: "aws"
        path: /root/.aws
  - name: "amazon/aws-cli"
    id: "publish-us-east-2"
    args:
      - s3api
      - --profile
      - cyral-production-public-assets
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-east-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-east-2"]
    volumes:
      - name: "aws"
        path: /root/.aws
      
  - name: "amazon/aws-cli"
    id: "upload-us-west-1"
    args:
      - s3api
      - --profile
      - cyral-production-public-assets
      - put-object
      - --bucket
      - cyral-public-assets-us-west-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda", "decrypt-aws-key"]
    volumes:
      - name: "aws"
        path: /root/.aws
  - name: "amazon/aws-cli"
    id: "publish-us-west-1"
    args:
      - s3api
      - --profile
      - cyral-production-public-assets
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-west-1
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-west-1"]
    volumes:
      - name: "aws"
        path: /root/.aws

  - name: "amazon/aws-cli"
    id: "upload-us-west-2"
    args:
      - s3api
      - --profile
      - cyral-production-public-assets
      - put-object
      - --bucket
      - cyral-public-assets-us-west-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --body
      - fail-open-lambda.zip
    waitFor: ["zip-lambda", "decrypt-aws-key"]
    volumes:
      - name: "aws"
        path: /root/.aws
  - name: "amazon/aws-cli"
    id: "publish-us-west-2"
    args:
      - s3api
      - --profile
      - cyral-production-public-assets
      - put-object-acl
      - --bucket
      - cyral-public-assets-us-west-2
      - --key
      - fail-open/fail-open-lambda-${TAG_NAME}.zip
      - --acl
      - public-read
    waitFor: ["upload-us-west-2"]
    volumes:
      - name: "aws"
        path: /root/.aws

